"""
Django settings for final project.

Generated by 'django-development_officer startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import environ

# Initialize environment variables
env = environ.Env()
environ.Env.read_env()  # Reads the .env file

# Use environment variables
BEEM_API_KEY = env('BEEM_API_KEY', default='default_api_key')
SECRET_KEY = env('SECRET_KEY', default='default_secret_key')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#kf!9_e^-#qhdx_fvx8t2674j5(dc=(_kcosl_dgjzlsus81yz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jazzmin',  # should be before 'django.contrib.admin'
    'django.contrib.admin',
    'trial',
    'widget_tweaks',
    'qrcode',
    'django_select2',
    'crispy_forms',
    'crispy_bootstrap4',
    'login_history',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = "bootstrap4"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'final.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'final.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',  # Use the MySQL engine
#         'NAME': 'rfms',                # Name of the database
#         'USER': 'root',             # MySQL user with access to the database
#         'PASSWORD': '',     # MySQL user's password
#         'HOST': 'localhost',                   # Database server address (or IP)
#         'PORT': '3306',                        # Default MySQL port
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'
# Define the full path to the 'static' directory
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'trial/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Where files are stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL to access files in the media directory
MEDIA_URL = '/media/'

# AUTH_USER_MODEL = 'trial.User'

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "My Admin",
    
    # Title on the brand, and the login screen (19 chars max)
    "site_header": "My Admin",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "path/to/logo.png",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to My Admin",

    # Copyright on the footer
    "copyright": "My Company Ltd",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "auth.User",

    # Field name on user model that contains avatar image
    "user_avatar": "profile_picture",

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Custom icons for side menu apps (Font Awesome icons e.g. "fas fa-user")
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    
    # Add your own branding
    "site_brand": "Jazzmin",
    
    # Customize the menu
    "custom_links": {
        "auth": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["auth.view_user"]
        }]
    },
    
    # Add another link to topbar
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/hackintoshrao/jazzmin", "new_window": True},
    ],
}



# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # For TLS
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'paschalmatiku6@gmail.com'
EMAIL_HOST_PASSWORD = 'wzkl kuwf reum xkgg'  
