# Generated by Django 5.0.1 on 2024-05-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DISTRICT_ACCOUNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('balance_amount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'District',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('group_account', models.CharField(max_length=20)),
                ('total_members', models.IntegerField(default=0)),
                ('group_no', models.IntegerField(default=0)),
                ('constitution', models.FileField(blank=True, null=True, upload_to='group_constitution/')),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Village',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Ward',
            },
        ),
        migrations.CreateModel(
            name='GroupAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='trial.group')),
            ],
            options={
                'db_table': 'GroupAccount',
            },
        ),
        migrations.CreateModel(
            name='GroupTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('transfer_in', 'Transfer In')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trial.district_account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.group')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='trial.groupaccount')),
            ],
            options={
                'db_table': 'GroupTransaction',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('member', 'member'), ('Development-Officer', 'Development-Officer'), ('Administrative-Secretary', 'Administrative-Secretary')], default='member', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('mwenyekiti', 'mwenyekiti'), ('mtunza_hazina', 'mtunza_hazina'), ('mwanachama', 'mwanachama')], default='mwanachama', max_length=14)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.profile')),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.profile')),
            ],
            options={
                'db_table': 'Sponsor',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.sponsor')),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='DISTRICT_TRANSACTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.district_account')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='trial.group')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.sponsor')),
            ],
            options={
                'db_table': 'DISTRICT_TRANSACTION',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trial.village'),
        ),
        migrations.AddField(
            model_name='village',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.ward'),
        ),
    ]
