# Generated by Django 5.0.1 on 2024-05-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsor',
            new_name='AdminstrativeSecretary',
        ),
        migrations.RenameField(
            model_name='grouptransaction',
            old_name='source_account',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='grouptransaction',
            name='destination_account',
        ),
        migrations.AlterModelTable(
            name='adminstrativesecretary',
            table='adminstrative_secretary',
        ),
        migrations.CreateModel(
            name='DevelopmentOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.profile')),
            ],
            options={
                'db_table': 'development_officers',
            },
        ),
    ]
