# Generated by Django 5.0.1 on 2024-05-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_rename_sponsor_adminstrativesecretary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district_transaction',
            old_name='sponsor',
            new_name='adminstrative_officer',
        ),
    ]
