# Generated by Django 5.0.1 on 2024-05-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0004_loanschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('district_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.district_transaction')),
                ('group_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.grouptransaction')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.member')),
            ],
        ),
    ]
